---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: submariner-operator
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: submariner-operator
  namespace: submariner-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - daemonsets
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - get
  - update
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - apps
  resources:
  - services
  verbs:
  - get
- apiGroups:
  - config.openshift.io
  resources:
  - networks
  verbs:
  - get
- apiGroups:
  - operator.openshift.io
  resources:
  - dnses
  verbs:
  - get
- apiGroups:
  - submariner.io
  resources:
  - brokers
  verbs:
  - get
- apiGroups:
  - submariner.io
  resources:
  - gateways
  verbs:
  - list
- apiGroups:
  - submariner.io
  resources:
  - servicediscoveries
  verbs:
  - delete
  - get
- apiGroups:
  - submariner.io
  resources:
  - submariners
  verbs:
  - get
- apiGroups:
  - submariner.io
  resources:
  - submariners/status
  verbs:
  - update
